// Proyectos_React/Wallapop/WALLAPOP__react/src/componentes/zonaPortal/AnuncioProducto/Producto.jsx
import './Producto.css';
import { useLoaderData, useNavigate } from 'react-router';
import useGlobalState from '../../../zustandGlobalState/globalState';
import fetchNode  from '../../../servicios/fetchNode';

function Producto(){
    const navigate = useNavigate();
    const producto = useLoaderData()[0];
    const { datosCliente:cliente, setDatosCliente } = useGlobalState();

    console.log('Producto cargado en loader:', producto);

   async function CrearNuevoChat() {
        console.log('Crear nuevo chat para producto:', producto);
        //1º comprobamos que no existe ya un chat abierto entre el cliente y el vendedor para este producto, si existe, redirigimos al cliente a ese chat en el buzón
        const chatExistente = cliente.misChats.find(chat => 
            chat.idVendedor === producto.idCliente && 
            chat.anuncioProducto.id === producto._id
        );
        if(chatExistente){
            console.log('Chat existente encontrado:', chatExistente);
            navigate('/Cliente/Dashboard/Buzon/' + chatExistente._id);
            return;
        }
        //----------------------------------------------------------------------------------------------------------------------------------------------------------
        const nuevoChat = {
            idComprador: cliente._id,
            idVendedor: producto.idCliente,
            anuncioProducto: {
                id: producto._id,
                titulo: producto.titulo,
                fotoPortada: producto.fotos && producto.fotos.length > 0 ? producto.fotos[0].data : null,
                precio: producto.precio,
                visitas: producto.visitas,
                likes: producto.likes                
            },
            mensajes: [], //<---- array de objetos: { contenido: string, timestamp: number, idEmisor: string, checked: boolean, tipoMensaje: 'texto' | 'oferta' | 'compra' }
            fechaInicioChat: Date.now(),
            fechaFinChat: 0
        };
        //mandamos a nodejs el nuevo chat para que lo añada a la base de datos y si ok, refrescamos datos del cliente en el estado global para que se muestre el nuevo chat en el buzón
        const resp = await fetchNode.ActualizarDatosCliente('AddChat', nuevoChat);
        if(resp.codigo===0){
            //refrescamos datos del cliente en el estado global para que se muestre el nuevo chat en el buzón con el _id de mongodb generado para el nuevo chat en nodejs
            setDatosCliente({ ...cliente, misChats: [...cliente.misChats, { ...nuevoChat, _id: resp.datos.idChat }] });
            navigate('/Cliente/Dashboard/Buzon');

        } else {
            alert('Error al intentar comunicarnos con el vendedor. Inténtalo de nuevo más tarde.');
        }    

    }

    return(
        <div className="container">
            <div className="row m-2">                
                <div className="col-md-8">
                    {producto.fotos && producto.fotos.length > 0 ? (
                        <div id="carouselExampleIndicators" className="carousel carousel-dark slide">
                            <div className="carousel-indicators">
                                {
                                    producto.fotos.map((foto, index) => (
                                        <button key={index}
                                                type="button"
                                                data-bs-target="#carouselExampleIndicators" 
                                                data-bs-slide-to={index} 
                                                className={index === 0 ? 'active' : ''} 
                                                aria-current={index === 0 ? 'true' : 'false'} 
                                                aria-label={`Slide ${index + 1}`}>
                                        </button>
                                    ))
                                }
                            </div>
                            <div className="carousel-inner">
                                {
                                    producto.fotos.map((foto, index) => (
                                        <div key={index} className={`carousel-item ${index === 0 ? 'active' : ''}`}>
                                            <img src={foto.data} className="d-block flex-fill w-50 h-50 rounded "  alt={foto.originalname} />
                                        </div>
                                    ))
                                }
                            </div>
                            <button className="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                                <span className="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span className="visually-hidden">Previous</span>
                            </button>
                            <button className="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                                <span className="carousel-control-next-icon" aria-hidden="true"></span>
                                <span className="visually-hidden">Next</span>
                            </button>
                        </div>                        
                    ) : (
                        <p>No hay fotos disponibles</p>
                    )
                    }

                </div>

                <div className="col-md-4">
                    <div className="card mb-3">
                        <div className="card-body">
                            <h5 className="card-title">{producto.titulo}</h5>
                            <h6 className="card-subtitle mb-2 text-body-secondary">{producto.estado}</h6>
                            <p className="card-text"><strong>{producto.precio} €</strong></p>
                            <div className="d-flex flex-column gap-2">
                                <button className="walla-button walla-button-primary">Comprar</button>
                                <button className="walla-button walla-button-secondary">Hacer oferta</button>
                            </div>
                        </div>
                    </div>

                    <div className="card mb-3">
                        <div className="row g-0">
                            <div className="col-md-4 d-flex justify-content-center align-items-center">
                                <img src="/images/inicio/empty-image.png" className="avatar-vendedor" alt="..."/>
                            </div>
                            <div className="col-md-8">
                                <div className="card-body">
                                    <div className="d-flex flex-row justify-content-between">
                                        <h5 className="card-title">Nombre vendedor</h5>
                                        <button type="button" className="btn-chat" onClick={ CrearNuevoChat }>Chat</button>
                                    </div>
                                    <p className="card-text">
                                        {
                                            Array.from({ length: 5 }, (_, i) => (
                                                <i key={i} className="fa-solid fa-star" style={{ color: '#000' }}></i>
                                            ))
                                        }
                                        <strong>5</strong>
                                        <span className="text-body-secondary">(100)</span>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

            <div className="row m-2">
                <div className="col">
                    <h5>Descripción</h5>
                    <p>{producto.descripcion}</p>
                    <hr />
                    <h5>Estado</h5>
                    <p>{producto.estado}</p>
                </div>
            </div>
        </div>
    );
}

export default Producto;

// Proyectos_Angular/Wallapop/WALLAPOP-AB__angular/src/app/componentes/zonaPortal/AnuncioProducto/producto.ts
import { Component, computed, effect, inject, Injector, OnInit, resource } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import IMiniProducto from '../../../modelos/IMiniProducto';
import IRestAPI from '../../../modelos/IRestAPI';
import { FecthNode}  from '../../../servicios/fecth-node';
import { NgClass } from '@angular/common';
import { StorageGlobal } from '../../../servicios/storage-global';
import ICliente, { IChat } from '../../../modelos/modelos_ORM/ICliente';

@Component({
  selector: 'app-producto',
  imports: [ NgClass],
  templateUrl: './producto.html',
  styleUrl: './producto.css',
})
export class Producto  {
  router=inject(Router);
  activatedRoute=inject(ActivatedRoute);
  fetchNode=inject(FecthNode);
  storageGlobal=inject(StorageGlobal);
  injector=inject(Injector);

  cliente=this.storageGlobal.GetDatosCliente()!.asReadonly();
  stars=Array.from({ length: 5 }, (_, i) => i + 1); // Array para representar las estrellas de valoración del producto, con valores del 1 al 5
  idCliente=this.activatedRoute.snapshot.paramMap.get('idCliente');
  idProducto=this.activatedRoute.snapshot.paramMap.get('idProducto');
  
  productoResourceRef=this.fetchNode.GetProductosVenta({ idProducto: this.idProducto!, idVendedor: this.idCliente! }); // Recurso para obtener los detalles del producto utilizando el idProducto e idCliente obtenidos de la ruta
  producto=computed<IMiniProducto | undefined>(() => {
    const resp=this.productoResourceRef.value() as IRestAPI; // Obtenemos la respuesta del recurso
    if(resp && resp.codigo===0 ){ // Si la respuesta es exitosa y contiene datos, devolvemos el producto
      return resp.datos!["productos"][0] as IMiniProducto;
    } else {
      return undefined; // En caso contrario, devolvemos undefined
    }
  });

  constructor(){
    effect(
      ()=>{
        const respGetProducto=this.productoResourceRef.value(); // Obtenemos los datos del producto a través del recurso
        console.log('Respuesta de la API al obtener el producto:', respGetProducto);
      }
    )
  }

  CrearNuevoChat(){
    
      console.log('crear nuevo chat para el producto:', this.producto());
      
      //1º comprobamos que no existe ya un chat abierto entre el cliente y el vendedor para este producto, si existe, redirigimos al cliente a ese chat en el buzón
      const chatExistente = this.cliente()!.misChats.find( (chat:IChat) =>  chat.datosVendedor.idVendedor === this.producto()!.idCliente &&  chat.anuncioProducto._id === this.producto()!._id );
      if(chatExistente){
          console.log('Chat existente encontrado:', chatExistente);
          this.router.navigate(['/Cliente/Dashboard/Buzon/',chatExistente._id]);
          return;
      }
      //----------------------------------------------------------------------------------------------------------------------------------------------------------
      const nuevoChat: IChat = {
          datosComprador: {
              idComprador: this.cliente()!._id,
              nombreCompleto: this.cliente()!.nombreCompleto
          },
          datosVendedor: {
              idVendedor: this.producto()!.idCliente,
              nombreCompleto: this.producto()!.nombreCompletoVendedor // Aquí podrías agregar el nombre completo del vendedor si lo tienes disponible
          },
          anuncioProducto: {
              _id: this.producto()!._id,
              titulo: this.producto()!.titulo,
              fotoPortada: this.producto()!.fotos && this.producto()!.fotos!.length > 0 ? this.producto()!.fotos![0].data : '',
              precio: this.producto()!.precio,
              visitas: this.producto()!.visitas,
              likes: this.producto()!.likes
          },
          mensajes: [], //<---- array de objetos: { contenido: string, timestamp: Date, enviadoPorComprador: boolean }
          fechaInicioChat: Date.now(),
          fechaFinChat: 0
      };
      //mandamos a nodejs el nuevo chat para que lo añada a la base de datos y si ok, refrescamos datos del cliente en el estado global para que se muestre el nuevo chat en el buzón
      const nuevoChatResource = this.fetchNode.ActualizarDatosCliente('AddChat', nuevoChat);
      effect(
        ()=>{
          const resp = nuevoChatResource.value() as IRestAPI;
          console.log('Respuesta de la API al crear un nuevo chat:', resp);

          if(resp.codigo===0){
            //refrescamos datos del cliente en el estado global para que se muestre el nuevo chat en el buzón con el _id de mongodb generado para el nuevo chat en nodejs
            this.storageGlobal.SetDatosCliente( { ...this.cliente()!, misChats: [...this.cliente()!.misChats, { ...nuevoChat, _id: resp.datos!["idChat"] }] });
            this.router.navigateByUrl(`/Cliente/Dashboard/Buzon/${resp.datos!["idChat"]}`);

          } else {
            alert('Error al intentar comunicarnos con el vendedor. Inténtalo de nuevo más tarde.');
          }
        }, { injector: this.injector })      
  }
}
